DROP TABLE IF EXISTS PET, USERS;

CREATE TABLE PET(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
BREED VARCHAR2(256)
);


CREATE TABLE USERS(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
 NAME VARCHAR2(256),
 AGE VARCHAR2(256),
 PET_ID BIGINT REFERENCES PET(ID)
);

